### ISSUE TITLE
I want to use your theme but.... IT DOESNT WORK!

### ISSUE THREAD

**Issue by ghost** [jeremyclark13/Techozoic-Fluid#7] opened 2013-03-13 15:07 UTC
I am a rookie, I admit it freely so developers get this. The laymen are not using your theme. BECAUSE IT DOESN'T WORK
sure it worked for 24 hours. But the sidebar never came on.(either one though at present we just used the right one)
Now the navigation bar is gone? No apparent reason, cant get it back
When I try and see themes-for support. Techozoic Settings
comes on for 1 second as a page, then vanishes. Thinking it was me or my firefox settings. I take my firefox all the way down to basics. Still cant see it to see if that will fix me?
I got a boss pist because she saw perfection last night when I showed her her page with your theme. Now its crap and we had to go back to something we didnt like
I am a rookie it shows. But even a rookie knows when a pile of crap falls on her.

**Comment by jeremyclark13** [comment] 2013-03-13 17:21
I'm sorry your having problems.  The sidebars are specific to each theme.  When you switch themes you'll have to setup your widgets again.  

I'm guessing with the options page not showing up that a plugin is conflicting with it.  Have you tried deactivating all the plugins then reactivate one at a time while testing the settings page.

I've but hundreds of hours into creating and supporting the theme for free, even if it is broken for you, calling it a pile of crap isn't the best way to get support.

**Comment by ghost** [comment] 2013-03-13 17:41
Well I have 31 plugins. care to be more specific? (See a list below)I cant go turning switches on and off because you have a conflict you didnt figure out ahead of time.The reason I call it that? your words now Crap.well gee, its supposed to be one click theme. one click theme turned to crap when I used it.I want to use it. my boss wants to use it. but I cant see what I am doing so how can I fix it!I dont like have to sign up an account to lodge a complaint either so another reason for calling it crap. Having an email address to ask for help much easier. you chose the path. you figure it out.And as you can se not all are activated NOW! So like I said you want to try you go find out.AffiliatesActivate | Delete The Affiliates plugin provides the right tools to maintain a partner referral program. Version 2.2.0 | By itthinx | Visit plugin siteSelect All in One ButtonsAll in One ButtonsActivate | Delete Quickly create amazing CSS3 buttons from the WordPress visual editor. Version 1.0 | By Brandon Bell | Visit plugin siteSelect Autonav Image Table Based Site NavigationAutonav Image Table Based Site NavigationActivate | Delete Displays child pages, posts, attached images or more, in a table of images or a simple list. Automatically resizes thumbnails. Version 1.5.4 | By William Lindley | Visit plugin siteSelect Background ManagerBackground ManagerActivate | Delete Background Manager allows you to display a random image as the website background at each visit or as a timed slideshow, without the need to edit the theme. Version 1.2.2 | By Mike Green (Myatu) | Visit plugin siteSelect Better WP SecurityBetter WP SecuritySettings | Deactivate Helps protect your Wordpress installation from attackers. Hardens standard Wordpress security by hiding vital areas of your site, protecting access to important files via htaccess, preventing brute-force login attempts, detecting attack attempts, and more. Version 3.4.8 | By Bit51.com | Visit plugin siteSelect Button It UpButton It UpActivate | Delete Make clickable things look clickable. For example, the Upload/Insert button. Version 1 | By Paris Vega | Visit plugin siteSelect Colorful Text WidgetsColorful Text WidgetsActivate | Delete Colorful text widget Version 2.0.0 | By iniyan | Visit plugin siteSelect Contact Form 7Contact Form 7Settings | Deactivate Just another contact form plugin. Simple but flexible. Version 3.3.3 | By Takayuki Miyoshi | Visit plugin siteSelect Cool Video GalleryCool Video GalleryActivate | Delete Cool Video Gallery, a video gallery plugin to manage video galleries. Feature to upload videos, attach Youtube videos, media files from library and group them into galleries is available. Option to play videos using Fancybox. Supports '.flv', '.mp4', '.m4v', '.mov' and '.mp3' files playback. Version 1.8 | By Praveen RajanSelect Disable Directory ListingsDisable Directory ListingsSettings | Deactivate Prevent virtual directory listing services from listing the contents of directories, and/or show a page in place of a directory's listing. Version 2.0 | By Scott Reilly | Visit plugin siteSelect Easy Digital Downloads - Affiliate Banners WidgetEasy Digital Downloads - Affiliate Banners WidgetActivate | Delete Adds some widgets with EDD banners links Version 1.0 | By Remi CorsonSelect Fast Secure Contact FormFast Secure Contact FormActivate | Delete Fast Secure Contact Form for WordPress. The contact form lets your visitors send you a quick E-mail message. Super customizable with a multi-form feature, optional extra fields, and an option to redirect visitors to any URL after the message is sent. Includes CAPTCHA and Akismet support to block all common spammer tactics. Spam is no longer a problem. Settings | Donate Version 3.1.8.1 | By Mike Challis | Visit plugin siteSelect FontFontSettings | Deactivate Now go to your home page. And click on "Font settings" in admin bar and choose some exciting font out of 1000+ availabile! And that's just the beginning! Version 5.25 | By Paweł Misiurski | Visit plugin siteSelect FontMeister - The Font Management PluginFontMeister - The Font Management PluginActivate | Delete FontMeister lets you preview, add and use fonts from popular sources on the web. It supports Google Web Fonts, Typekit, Fontdeck and Font Squirrel. Version 1.04 | By Sayontan Sinha | Visit plugin siteSelect Jetpack by WordPress.comJetpack by WordPress.comSettings | Deactivate Bring the power of the WordPress.com cloud to your self-hosted WordPress. Jetpack enables you to connect your blog to a WordPress.com account to use the powerful features normally only available to WordPress.com users. Version 2.2 | By Automattic | Visit plugin siteSelect MembershipMembershipDeactivate The most powerful, easy to use and flexible membership plugin for WordPress, Multisite and BuddyPress sites available. Offer downloads, posts, pages, forums and more to paid members. Version 2.0.7 | By Barry (Incsub/WPMU DEV) | Visit plugin siteSelect mPress BannersmPress BannersDeactivate Easily manage pop-up banners on your site. Version 0.1 | By Micah WoodSelect NextGEN GalleryNextGEN GalleryDeactivate A NextGENeration Photo Gallery for WordPress Version 1.9.12 | By Photocrati | Visit plugin site | Overview | Get help | ContributeSelect Paid Memberships ProPaid Memberships ProActivate | Delete Plugin to Handle Memberships Version 1.5.9.2 | By Stranger Studios | Visit plugin siteSelect Rate My WhateverRate My WhateverActivate | Delete Adds the option to rate posts. Version 0.2-Beta | By Henric Johansson, henric-johansson@hotmail.comSelect Site Creator UltimateSite Creator UltimateActivate | Delete Advanced Page & Post Layout Editor For Wordpress Version 2.2 | By 1customize | Visit plugin siteSelect Video Sidebar WidgetsVideo Sidebar WidgetsActivate | Delete Video Sidebar Widgets to display videos such as Vimeo, YouTube, MySpace Videos etc. Now with added shortcode and quicktag to embed video in post and page content. Version 5.3 | By Denzel Chia | Visit plugin siteSelect Visual Editor Font SizeVisual Editor Font SizeDeactivate Allows you to change the font size of the visual editor Version 0.2 | By Nikolay Bachiyski | Visit plugin siteSelect vSlidervSliderActivate | Delete Implementing a featured image gallery into your WordPress theme has never been easier! Showcase your portfolio, animate your header or manage your banners with vSlider.Create unlimited image sliders, the best wordpress image slider plugin vSlider by VibeThemes. Version 4.1.2 | By Mr.Vibe | Visit plugin siteSelect Web FontsWeb FontsActivate | Delete The canonical Web Fonts plugin for WordPress. This plugin includes support for Fonts.com and Google web fonts and supports a variety of web font providers via an easy to implement plugin architecture. Version 1.1.5 | By Nick Ohrn of Plugin-Developer.com | Visit plugin siteSelect WordPress FontSize AdjustWordPress FontSize AdjustActivate | Delete Adds Stateful Fontsize Adjustment Classes to the body of the Website Version 0.6.5 | By Circle Tree, LLC | Visit plugin siteSelect WP-TopBarWP-TopBarActivate | Delete Creates a TopBar that will be shown at the top of your website. Customizable and easy to change the color, text, image and link. Version 4.14 | By Bob Goetz | Visit plugin siteSelect WP Google FontsWP Google FontsActivate | Delete The Wordpress Google Fonts Plugin makes it even easier to add and customize Google fonts on your site through Wordpress. Version v3.1.1 | By Adrian Hanft, Aaron Brown | Visit plugin siteSelect WP Photo Album PlusWP Photo Album PlusDeactivate Easily manage and display your photo albums and slideshows within your WordPress site. Version 4.9.11 | By J.N. Breetvelt a.k.a OpaJaap | Visit plugin site | Donate USD | Donate EUR | Documentation and examplesThere is a new version of WP Photo Album Plus available. View version 4.9.12 details or update now.Please Read the Changelog Details Before Upgrading.Select wpStoreCart - Ajax EcommercewpStoreCart - Ajax EcommerceActivate | Delete

-------- Original Message --------
Subject: Re: [Techozoic-Fluid] I want to use your theme but.... IT
DOESNT WORK! (#7)

**Comment by jeremyclark13** [comment] 2013-03-13 18:01
You can select groups of plugins at a time.  You don't have to deactivate them all one by one.  

I don't have time nor do I care to test with all these plugins, I can't fix problems that I didn't cause.  The theme is double checked by a group of theme developers everytime a new version is released.  Plugins don't have the same standards so many more plugins are poorly coded and will cause problems.

As far as registering an account, you can thank spammers for that.

**Comment by ghost** [comment] 2013-03-13 18:09
so your only suggestion is turn off everything? What happens when it turns off something I need?Well blame spammers then for the crapSince it aint me it aint you its them.So dont get mad at me for calling it like I see it your passing the buck now. someone who want s to sue your product cant. and your too busy to help. that will go far in the industry.Your to small for me to worry about so your on your own.Great thanks for the help. I am sure i will be just endorsing your theme wherever  i go.

-------- Original Message --------
Subject: Re: [Techozoic-Fluid] I want to use your theme but.... IT
DOESNT WORK! (#7)

**Comment by jeremyclark13** [comment] 2013-03-13 18:18
My suggestion was to turn everything off then turn it back on one by one to isolate the problem.  That is standard procedure for isolating a problem like your having.  

As far as not taking the time even if I did install all those plugins I still might now find the problem, because every hosting provider sets up things differently.  

I'd be more than glad to help you, but belittling someone's hard work doesn't exactly but them in the best mood.  I really would like to help you get it going so that's why I asked you to do what I did.  If your not willing to try then I really can't help anymore.

**Comment by ghost** [comment] 2013-03-13 18:31
I get angry when I have to jump thru 3 hoops just to get real help.I am willing to bet I do this AND NOTHING changes.care to wager?then what if I am right?

-------- Original Message --------
Subject: Re: [Techozoic-Fluid] I want to use your theme but.... IT
DOESNT WORK! (#7)

**Comment by jeremyclark13** [comment] 2013-03-13 18:36
If nothing changes then we can go from there, because then I would have ruled out what usually cause 90% of problems.

**Comment by ghost** [comment] 2013-03-13 21:02
Oh gee look, that didnt workWhat a surpriseAnd now because I deactivate all per your request I have to go fix all those problems. Cant imagine why I did not want to do that?Gee thanks

-------- Original Message --------
Subject: Re: [Techozoic-Fluid] I want to use your theme but.... IT
DOESNT WORK! (#7)

**Comment by ghost** [comment] 2013-03-14 23:26
Okay you either missed it or ignored it. Did exactly what you said. NO CHANGE
reset system No change
Used a diff browser
NO CHANGE

Getting a theme here?

Reset all settings on your Theme, and while most reset NOT all did. Like what? The title bar is Gone. it vanished yesterday, and even with reset settings. GONE. So cant use sidebars, cant use technozoig settings (which I believe will let me use sidebar) and now title bar is gone no matter what color you make it

**Comment by jeremyclark13** [comment] 2013-03-15 00:41
Even if you can't get to the the settings page you should still be able to use the the customizer. On the appearance page by the theme picture there is a customize link. This page has most of the basic options on it. 

There is an option to show sidebars on the home page, it should be checked by default. There is also one to show sidebars on single pages. 

When you say title bar do you mean the title above the homepage content, if so that's by design. The home page title should be the title of the site. If you need a header you can simply add it to the content of the home page. 

What is the site where the theme is activated, I might be able to see the problem on the front end of the site.

**Comment by ghost** [comment] 2013-03-15 02:53
I have been using the customizing page? No the bar with the links to other pages. It was there now it is gone. Sidebars never appeared on the title page only the other pages. 
And it really does matter you cant access the layout area.

So its still your program at fault. And  gee no apologies for me wasting all my time yesterday following your advice that was Oh WRONG!
You said I was overly Harsh? Well did everything you said and the page wont function.
So how am I being harsh now?
When we first used it, the l;ink bar lets call it at top was one primary reason she wanted your theme. When it went blank she got mad. When her slide show and twitter feed only were visible on other pages not front page more so.

Yeah I used customizer trying to get that to work. Never did on static page
But I said that

Go daddy is the provider

Only other issue to note. the media picture I inserted when on your page gets made xtra small. It returns to its orig size on every other theme

But dont treat me like a fool who doesnt know how to turn the lights on. I am not crying wolf here. I have tried for hours and hours to get your theme to work before asking for your help. Which I thought was the reason you put a link on there to ask? Apparently not?

**Comment by jeremyclark13** [comment] 2013-03-15 03:29
Ok you talking about the navigation menu.  It is created and assigned under the Appearance->Menus page.  You'll need to either create a new menu or if you've already created one assign it to the Header Navigation area.  If you've created one but didn't assign any pages to it then that is why that would be why it disappeared.

Go daddy shouldn't be a problem.  I've personally setup the theme on their hosting without problems.  I was actually asking about a link to the website your trying to get setup.  I might be able to help if I saw the actual site with the theme activated.

The featured image is setup so that it fits within the content area and doesn't overflow into the sidebars.  If you need larger images you can always insert the image into the content at whatever size you like instead of using the featured image.

I'm not trying to treat you like a fool, I'm really trying to help.  I'm sorry that what I thought was the problem didn't help, I've been working with WordPress for quite a while and usually problems like what you described are caused by plugin conflicts.

**Comment by ghost** [comment] 2013-03-15 04:29
I am not trying to set up anything. Website has been up for a month. we were trying to fit a good theme.I didnt assign anything. It took the settings that were there and ran fine for 24 hours. And now its gone. even after resetNothing was ever assigned. just defaulted

-------- Original Message --------
Subject: Re: [Techozoic-Fluid] I want to use your theme but.... IT
DOESNT WORK! (#7)

**Comment by ghost** [comment] 2013-03-15 17:46
Your still assuming things.I know about images. Thats why we loaded the header into the content instead of your header. No adjustments a re possible in the header.So thats why its left blank.The sidebar never appeared from the start. I am not gonna leave my pages up when they dont work just so you can look at them and deiced i am not an idiot.I can give you address, but it is not gonna make a difference, since I wont load a broken themeI also was just sent 200 pics I have to fix watermark ans send back. So I am not gonna wait and see for a broken themeLook you tell me. I have tried it with and without the media. I clear my cache so it isnt me.Something else is wrong fundamentally with the designCould it be browser/ If it was then how come it did it with Chrome?fitcougar.com

-------- Original Message --------
Subject: Re: [Techozoic-Fluid] I want to use your theme but.... IT
DOESNT WORK! (#7)

**Comment by ghost** [comment] 2013-03-19 22:32
Well gee its still not working. Everything you suggest makes no difference. so blaming me or the plugins I use didnt work whats next?
reading your own change log? I think you should with draw this plugin for a while buddy. Clearly you dont do customer service and this thing has so many bugs in it you need a staff of 20 to handle all the issues. You created it so guess what you get to deal with it

**Comment by jeremyclark13** [comment] 2013-03-20 00:26
Again I'm sorry it's not working for you, I've been trying my best to help.  You really haven't given my any useful info to be able to even speculate what the problem might be other than a problem with a plugin, which is normally the cause of blank pages.  If you'd like I'd be glad to login and see if I can figure out the problem.  I'd need to activate the theme for a few minutes.  {Email removed}.

**Comment by ghost** [comment] 2013-03-20 13:07
Appreciate offer. But no point in having it done for me. I will have to fix it next time. And I have to tell the owner something. Think its best we move on.Looking at a similar theme. it flat said. Upgrade to pro or make a donation for more options. So whether intentional or not thats why a screen on your theme is not accessibleAs for your help.Its not help when you say do this. I indicate I am a rookie. You have to instruct a person how to do something. When they clearly dont know what is what. Like the navigational menuYou didnt ask what I did you assumed. the first part you assumed I didnt know about. I did and tried there 6 times before contacting you. Then you said wel do this this and this? Not saying where to do that part how to do that part or anything. SO when I look on your change log? Well Im not updating this for two lousy messages. and this doesnt need to get fixed?Dude, if this is your baby? You have to wipe its ass no matter how absurd it is. That is the nature of the beast. If you cant do that/ You dont need to be in the theme business. There are people worse than me out there trying. When they contact you for support? they expect customer service. It doesnt matter if you dont like it dont want to. Once you put you out into your baby. Its all on you. pass or fail rests wiht how you deal with it. Right now? FAIL

-------- Original Message --------
Subject: Re: [Techozoic-Fluid] I want to use your theme but.... IT
DOESNT WORK! (#7)

**Comment by jeremyclark13** [comment] 2013-03-20 13:25
I don't know where you found this message but I certainly didn't write that.  

> SO when I look on your change log? Well Im not updating this for two lousy messages. and this doesnt need to get fixed?

But if you've found another theme then I hope you have more success with it.

**Closed as completed by jeremyclark13** 2013-03-20 13:25 UTC

**Comment by ghost** [comment] 2013-03-21 01:05
You closed it as UNRESOLVED
Just so we are fair
Never fixed, never looked at, not enough time to help other then to ask for my password info? nice

**Comment by jeremyclark13** [comment] 2013-03-21 01:16
Yes I do fully understand the problem is unresolved, I really do wish I could help but I closed it because you said you found another theme. If you still want to pursue using my theme I'll need more info hence why I offered to login and look at the problem first hand. I understand not wanting to give out credentials but since you can't leave the theme activated I can't really look at the problem any other way.

**Comment by Mister3** [comment] 2013-03-21 02:07
Ghost --
You need to take a chill pill. I've been using the free version of Techozoic Fluid for a couple of years. I've got over two dozen sites running on Techozoic Fluid -- and I've never written a line of code. Techozoic Fluid is a phenomenal theme and it's spoiled me from using any other themes because of the power and flexibility that it provides.

The few times that I've needed help with the theme, the author has been extremely helpful -- and my first problem with this theme was completely self inflicted.

I feel sorry for you and the people around you if you're going to go around and abusing people and their products when they've made them available to you for free.

If it were up to me, I'd close this ticket and ban you from the system, so be polite and civil and you may still be able to get help.

This is a phenomenal theme, and you're being ridiculous in your accusations and expectations. In fact, you've inspired me to donate to the author for the good work he's done.

**Comment by Mister3** [comment] 2013-03-21 02:14
Hey Ghost!
I just donated $50 to the theme author and dedicated it to you! What have you done for the author aside from being a pain in the butt?
